[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = true

[[inputs.ping]]
  urls = ["192.168.3.144", "192.168.3.204"]
  count = 3
  timeout = 2.0
  [inputs.ping.tags]
    role = "server"

[[inputs.ping]]
  urls = ["192.168.3.111", "192.168.3.90"]
  count = 3
  timeout = 2.0
  [inputs.ping.tags]
    role = "camera"

[[inputs.ping]]
  urls = ["192.168.3.249"]
  count = 3
  timeout = 2.0
  [inputs.ping.tags]
    role = "switch"

[[outputs.influxdb_v2]]
  urls = ["http://127.0.0.1:8088"]
  token = "apiv3_pPignodoymU5KNfoig3neUB3xyinBBoWRysCbaq32OqNMxLZikuyLB5C1_O1U3XoGt9CZVL7b0DTVOmcgMbcuQ"
  organization = "default"
  bucket = "camera_monitoring"
