{
 "title": "Comprehensive Monitoring (Explicit Panels)",
 "tags": [
  "monitoring",
  "dynamic",
  "influxql",
  "explicit-roles"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "device_type",
    "label": "Device Type (Table Filter)",
    "query": "SHOW TAG VALUES WITH KEY = \"role\""
   }
  ]
 },
 "panels": [
  { "title": "GLOBAL HEALTH", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TOTAL DEVICES",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total",
     "query": "SELECT count(\"last\") FROM (SELECT last(\"percent_packet_loss\") FROM \"ping\" WHERE time > now() - 2m GROUP BY \"url\")"
    }
   ]
  },
  {
   "title": "ONLINE",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Online",
     "query": "SELECT count(\"last\") FROM (SELECT last(\"percent_packet_loss\") FROM \"ping\" WHERE \"percent_packet_loss\" < 100 AND time > now() - 2m GROUP BY \"url\")"
    }
   ]
  },
  {
   "title": "OFFLINE",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Offline",
     "query": "SELECT count(\"last\") FROM (SELECT last(\"percent_packet_loss\") FROM \"ping\" WHERE \"percent_packet_loss\" = 100 AND time > now() - 2m GROUP BY \"url\")"
    }
   ]
  },
  {
   "title": "% AVAILABILITY",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Availability",
     "query": "SELECT mean(\"percent_packet_loss\") * -1 + 100 FROM \"ping\" WHERE $timeFilter"
    }
   ]
  },
  { "title": "SERVER HEALTH", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "SERVER ONLINE",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Online",
     "query": "SELECT count(\"last\") FROM (SELECT last(\"percent_packet_loss\") FROM \"ping\" WHERE \"percent_packet_loss\" < 100 AND \"role\" = 'server' AND time > now() - 2m GROUP BY \"url\")"
    }
   ]
  },
  {
   "title": "SERVER OFFLINE",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Offline",
     "query": "SELECT count(\"last\") FROM (SELECT last(\"percent_packet_loss\") FROM \"ping\" WHERE \"percent_packet_loss\" = 100 AND \"role\" = 'server' AND time > now() - 2m GROUP BY \"url\")"
    }
   ]
  },
  {
   "title": "SERVER AVAILABILITY",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Availability",
     "query": "SELECT mean(\"percent_packet_loss\") * -1 + 100 FROM \"ping\" WHERE \"role\" = 'server' AND $timeFilter"
    }
   ]
  },
  { "title": "CAMERA HEALTH", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CAMERA ONLINE",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Online",
     "query": "SELECT count(\"last\") FROM (SELECT last(\"percent_packet_loss\") FROM \"ping\" WHERE \"percent_packet_loss\" < 100 AND \"role\" = 'camera' AND time > now() - 2m GROUP BY \"url\")"
    }
   ]
  },
  {
   "title": "CAMERA OFFLINE",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Offline",
     "query": "SELECT count(\"last\") FROM (SELECT last(\"percent_packet_loss\") FROM \"ping\" WHERE \"percent_packet_loss\" = 100 AND \"role\" = 'camera' AND time > now() - 2m GROUP BY \"url\")"
    }
   ]
  },
  {
   "title": "CAMERA AVAILABILITY",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Availability",
     "query": "SELECT mean(\"percent_packet_loss\") * -1 + 100 FROM \"ping\" WHERE \"role\" = 'camera' AND $timeFilter"
    }
   ]
  },
  { "title": "SWITCH HEALTH", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "SWITCH ONLINE",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Online",
     "query": "SELECT count(\"last\") FROM (SELECT last(\"percent_packet_loss\") FROM \"ping\" WHERE \"percent_packet_loss\" < 100 AND \"role\" = 'switch' AND time > now() - 2m GROUP BY \"url\")"
    }
   ]
  },
  {
   "title": "SWITCH OFFLINE",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Offline",
     "query": "SELECT count(\"last\") FROM (SELECT last(\"percent_packet_loss\") FROM \"ping\" WHERE \"percent_packet_loss\" = 100 AND \"role\" = 'switch' AND time > now() - 2m GROUP BY \"url\")"
    }
   ]
  },
  {
   "title": "SWITCH AVAILABILITY",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Availability",
     "query": "SELECT mean(\"percent_packet_loss\") * -1 + 100 FROM \"ping\" WHERE \"role\" = 'switch' AND $timeFilter"
    }
   ]
  },
  { "title": "TRENDS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Offline Devices (Trend - Global)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "alias": "Offline Count",
     "query": "SELECT count(\"percent_packet_loss\") FROM \"ping\" WHERE \"percent_packet_loss\" = 100 AND $timeFilter GROUP BY time($__interval) fill(0)"
    }
   ]
  },
  { "title": "DETAILS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Device Status Table",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "alias": "status",
     "query": "SELECT last(\"percent_packet_loss\") as \"status\" FROM \"ping\" WHERE \"role\" =~ /^$device_type$/ AND $timeFilter GROUP BY \"url\", \"role\""
    }
   ]
  }
 ]
}