{
 "title": "Comprehensive Monitoring (Flux)",
 "tags": [
  "camera",
  "monitoring",
  "comprehensive"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "device_type",
    "query": "\n  from(bucket: \"camera_monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ping\")\n  |> keyValues(key: \"role\")\n  |> keep(columns: [\"_value\"])\n  |> distinct()\n  "
   }
  ]
 },
 "panels": [
  { "title": "GLOBAL HEALTH", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TOTAL DEVICES",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\n                from(bucket: \"camera_monitoring\")\n                |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n                |> filter(fn: (r) => r[\"_measurement\"] == \"ping\")\n                |> filter(fn: (r) => r[\"_field\"] == \"percent_packet_loss\")\n                |> filter(fn: (r) => contains(value: r[\"role\"], set: ${device_type:json}))\n                |> group(columns: [\"url\"])\n                |> last()\n                |> group()\n                |> count()\n                |> yield(name: \"total_devices\")\n            "
    }
   ]
  },
  {
   "title": "ONLINE",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\n                from(bucket: \"camera_monitoring\")\n                |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n                |> filter(fn: (r) => r[\"_measurement\"] == \"ping\")\n                |> filter(fn: (r) => r[\"_field\"] == \"percent_packet_loss\")\n                |> filter(fn: (r) => contains(value: r[\"role\"], set: ${device_type:json}))\n                |> filter(fn: (r) => r[\"_value\"] < 100)\n                |> group(columns: [\"url\"])\n                |> last()\n                |> group()\n                |> count()\n                |> yield(name: \"online_count\")\n            "
    }
   ]
  },
  {
   "title": "OFFLINE",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\n                from(bucket: \"camera_monitoring\")\n                |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n                |> filter(fn: (r) => r[\"_measurement\"] == \"ping\")\n                |> filter(fn: (r) => r[\"_field\"] == \"percent_packet_loss\")\n                |> filter(fn: (r) => contains(value: r[\"role\"], set: ${device_type:json}))\n                |> filter(fn: (r) => r[\"_value\"] == 100)\n                |> group(columns: [\"url\"])\n                |> last()\n                |> group()\n                |> count()\n                |> yield(name: \"offline_count\")\n            "
    }
   ]
  },
  {
   "title": "% AVAILABILITY",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\n                from(bucket: \"camera_monitoring\")\n                |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n                |> filter(fn: (r) => r[\"_measurement\"] == \"ping\")\n                |> filter(fn: (r) => r[\"_field\"] == \"percent_packet_loss\")\n                |> filter(fn: (r) => contains(value: r[\"role\"], set: ${device_type:json}))\n                |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n                |> map(fn: (r) => ({ r with _value: 100.0 - r._value }))\n                |> yield(name: \"availability\")\n            "
    }
   ]
  },
  { "title": "CATEGORY HEALTH", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "SELECTED DEVICES HEALTH",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\n                from(bucket: \"camera_monitoring\")\n                |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n                |> filter(fn: (r) => r[\"_measurement\"] == \"ping\")\n                |> filter(fn: (r) => r[\"_field\"] == \"percent_packet_loss\")\n                |> filter(fn: (r) => contains(value: r[\"role\"], set: ${device_type:json}))\n                |> filter(fn: (r) => r[\"_value\"] < 100)\n                |> group(columns: [\"url\"])\n                |> last()\n                |> group()\n                |> count()\n                |> yield(name: \"devices_online\")\n            "
    },
    {
     "query": "\n                from(bucket: \"camera_monitoring\")\n                |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n                |> filter(fn: (r) => r[\"_measurement\"] == \"ping\")\n                |> filter(fn: (r) => r[\"_field\"] == \"percent_packet_loss\")\n                |> filter(fn: (r) => contains(value: r[\"role\"], set: ${device_type:json}))\n                |> filter(fn: (r) => r[\"_value\"] == 100)\n                |> group(columns: [\"url\"])\n                |> last()\n                |> group()\n                |> count()\n                |> yield(name: \"devices_offline\")\n            "
    }
   ]
  },
  { "title": "TREND", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Offline Devices (Trend)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "query": "\n                from(bucket: \"camera_monitoring\")\n                |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n                |> filter(fn: (r) => r[\"_measurement\"] == \"ping\")\n                |> filter(fn: (r) => r[\"_field\"] == \"percent_packet_loss\")\n                |> filter(fn: (r) => contains(value: r[\"role\"], set: ${device_type:json}))\n                |> filter(fn: (r) => r[\"_value\"] == 100)\n                |> aggregateWindow(every: v.windowPeriod, fn: count, createEmpty: false)\n                |> yield(name: \"offline_trend\")\n            "
    }
   ]
  },
  { "title": "DEVICE STATUS TABLE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Device Status Table",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "query": "\n                from(bucket: \"camera_monitoring\")\n                |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n                |> filter(fn: (r) => r[\"_measurement\"] == \"ping\")\n                |> filter(fn: (r) => r[\"_field\"] == \"percent_packet_loss\")\n                |> filter(fn: (r) => contains(value: r[\"role\"], set: ${device_type:json}))\n                |> last()\n                |> map(fn: (r) => ({\n                    r with\n                    status: if r._value == 100.0 then 1 else 0,\n                    device_ip: r.url,\n                    role: r.role\n                }))\n                |> keep(columns: [\"_time\", \"device_ip\", \"role\", \"status\"])\n            "
    }
   ]
  }
 ]
}